version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: linkedin-scraper:local
    ports:
      - "8080:8080"    # nginx / Flask
      - "6901:6081"    # noVNC websockify (mapped host 6901 -> container 6081)
      - "5900:5900"    # VNC
    environment:
      - WEBSOCKIFY_URL=http://localhost:6901/vnc.html?host=127.0.0.1&port=5900
    shm_size: '1gb'
    restart: unless-stopped
